name: shield
description: "A new open source project to keep privacy on first priority"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^9.0.0
  get_it: ^7.2.0
  provider: ^6.0.0
  flutter_localization: ^0.2.2
  supabase_flutter: ^2.6.0
  firebase_core: ^2.12.0
  firebase_analytics: ^10.0.0
  firebase_crashlytics: ^3.0.0
  intl: ^0.19.0
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.3
  flutter_lints: ^3.0.0
  mockito: ^5.1.0
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true